

services:
  # Spring Boot uygulaması
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://teknotik-backend-db-1:5432/postgres"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Rizamustang41"
    depends_on:
      - db

  # PostgreSQL veritabanı
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "Rizamustang41"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
