services:
  # Spring Boot uygulaması
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"  # db:5432 adresi ile bağlan
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Rizamustang41"
    depends_on:
      - db

  # PostgreSQL veritabanı
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "Rizamustang41"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"  # Bu port dışarıya açılıyor ancak konteyner içinde yine 5432'yi kullanacak
